### ISSUE TITLE
Crate unpack error moving from Mac to Windows 10

### ISSUE THREAD

**Issue by rompgadgets** [drmikehenry/romt#12]
Hello,

Ran into a little trouble following the readme to unpack an export created on a Mac.  I'm using the latest release and ran the following:
```
romt crate -v --keep-going init export
romt toolchain -v -s nightly -t windows download pack
romt rustup -v -s stable -t windows download pack
```

Everything downloaded as expected and I then went to move the resulting `.tar.gz` files to another laptop.  Per the instructions I then ran (using the latest release romt-0.3.1 for windows):
```
romt.exe toolchain -v unpack 
```
with no errors.  Next,
```
romt.exe rustup -v unpack 
```
with no errors. And finally,
```
romt.exe crate -v --keep-going init-import import
```
and get the following error:
```
init-import...
create index repository at 'git\\crates.io-index':
  remote add origin E:\mirror\git\crates.io-index\origin.bundle
create crates directory at 'crates':
import...
unpack...
error: INDEX remote ``origin`` must have ``url`` as a local file
```

**Comment by drmikehenry** [comment]
I see there's a problem on Windows here:
https://github.com/drmikehenry/romt/blob/main/src/romt/crate.py#L765

The intent is to ensure only local paths are in use for the URL, but windows
drive letters cause `urllib.parse.urlparse(url)` to return the drive
letter as `parsed.scheme`.

While a fix is pending, you can work around this issue by editing
`git\crates.io-index\.git\config` and deleting the `E:` in the `url`.

**Comment by brooke-peterson** [comment]
That file isn't created until ```romt.exe crate -v --keep-going init-import import``` is run, so editing and re-running results in ```index directory git\crates.io-index already exists```.

Another temporary workaround is to use Cygwin or Git Bash, WSL: anything that doesn't use the DOS naming scheme of ``driveletter:```

**Comment by drmikehenry** [comment]
Sorry; I was hurrying before work today and didn't have time to be more
explicit.  The `init-import` step can be separated from `import`; in between the
steps is where you'd fix the `url`:

```
romt.exe crate -v --keep-going init-import
# Fix the `url` here.
romt.exe crate -v --keep-going import
```

(Now I'm hurrying before dinner :-))

**Comment by drmikehenry** [comment]
Version 0.3.2 should fix the problem with drive letters in Windows.paths for the `origin` URL.  Thanks for reporting the issue :-)

**Comment by drmikehenry** [comment]
Closing with the assumption that version 0.3.2 fixes the issue.
