### ISSUE TITLE
What means ConnectTimeout('') and ReadTimeout('') ?

### ISSUE THREAD

**Issue by weerdy15** [drmikehenry/romt#16]
I had errors like this
```
error: failed to download https://static.crates.io/crates/lancelot-flirt/lancelot-flirt-0.6.0.crate; exception details ConnectTimeout('')
```
and this
```
error: failed to download https://static.crates.io/crates/lc3tools-sys/lc3tools-sys-1.0.6-alpha4.crate; exception details ReadTimeout('')
```
while mirroring crates.io crate files.
Is this `403: Forbidden` as mentioned in README, or something else?
The command i used:
```sh
E:\rust_crates>romt crate -v --keep-going update -j=64
```
The command prompt is opened as a normal user, not admin.

**Comment by drmikehenry** [comment]
Both of the URLs you mention are available for download from `static.crates.io` (i.e., they aren't among the ones that give a 403 error).  You can try downloading them using a web browser, or with `wget` or `curl`, e.g.:

```sh
curl -O https://static.crates.io/crates/lancelot-flirt/lancelot-flirt-0.6.0.crate

wget https://static.crates.io/crates/lancelot-flirt/lancelot-flirt-0.6.0.crate
```

If timeouts are uncommon, you can possibly just re-try the download operation (perhaps using a smaller value for the `-j` switch).  This might help determine the characteristics of your network that are causing the timeouts.

Also, if you are using a proxy, you might want to read <https://github.com/drmikehenry/romt/blob/1420befe1fcba01d8dfdc27f2ff85f43bb4e2284/README.rst#proxy-server-troubleshooting> for some hints another user provided for proxy-related problems.  (I haven't tested with a proxy personally.)

`ConnectTimeout` and `ReadTimeout` are timeout errors from the `httpx` library Romt uses for downloading.  Timeouts for `httpx` may be disabled as explained in <https://www.python-httpx.org/advanced/#timeout-configuration> by passing `timeout=None` when creating a client.  To try this, you can edit this line:

https://github.com/drmikehenry/romt/blob/1420befe1fcba01d8dfdc27f2ff85f43bb4e2284/src/romt/download.py#L24

And change it to:

```python
        self._client = httpx.AsyncClient(timeout=None)
```

**Comment by weerdy15** [comment]
Resolved. Thanks! (The problem was in power of my pc. I guess i requested too many jobs and overloaded my network (ConnectTimeout) and disk (ReadTimeout))

**Comment by drmikehenry** [comment]
Romt-0.4.0 now has a `--timeout` switch to adjust download timeouts.  In addition, the default timeout was changed from the `httpx` default of five seconds to sixty seconds.  See the `README.rst` for details.
