### ISSUE TITLE
toolchain - nightly and stable mix/share targets

### ISSUE THREAD

**Issue by MrWorldwideMkII** [drmikehenry/romt#17]
When running 
```
romt toolchain \
    -v \
    -s nightly \
    -s stable \
    -t all \
    download pack 
```

Everything seems to run fine.

Then after transferring the tar to the offline machine and running `romt toolchain -v unpack` everything seems to be working correctly until it breaks when it starts verifying the stable version, with the following error:
```
[verify] dist/2022-04-07/channel-rust-stable.toml
    ident: stable-2022-04-07(1.60.0)
error: target 'x86_64-unknown-none' not found in manifest
```

This appears to be a target that exists in the nightly release (17/04/2022) but doesn't exist in the stable release.
(The target appears in the manifest of the nightly toolchains and is also downloaded/extracted/verified but doesn't appear anywhere in the stable release)

My current workaround is downloading the nightly and stable versions separately into different archives.

**Comment by drmikehenry** [comment]
Thanks for pointing out this issue.  I never download all targets, so I hadn't come across the problem.  Romt has independent switches for `--select` and `--targets`, so typically the list of targets must be the same for each selected spec; but when ``--target all`` is used, the list can vary if one spec supports more targets than another.  Romt 0.4.0 now detects this case during unpacking by checking whether all targets for each spec are present in the detected targets, and converting the target list back to ``all``.

**Comment by drmikehenry** [comment]
Closing with the assumption that Romt-0.4.0 fixes this issue.
