### ISSUE TITLE
Offline mirroring of a subset of crates.io

### ISSUE THREAD

**Issue by jblestang** [drmikehenry/romt#3]
Is there anyway to mirror only a subset of crates.io and their dependencies?

**Comment by drmikehenry** [comment]
No, Romt is intended for mirroring all of crates.io.  It doesn't have any features for mirroring subsets or tracking dependencies.  But recently Cargo has gotten a new `cargo vendor` command that might help: https://doc.rust-lang.org/nightly/cargo/commands/cargo-vendor.html
